version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    reviewers:
      - "pnodet"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Paris"
